import json
import uuid
from datetime import datetime
from pathlib import Path
from agents.project_loader import ProjectInventory, ObjectType
from agents.validation_agent import ValidationResult
from agents.dependency_agent import DependencyGraph
from parser.ast_parser import detect_snowflake_features

REPORT_VERSION = "1.0.0"

_ARCH_MAP = [
    ("Stream", "Delta Change Data Feed", "Enable Change Data Feed on source tables and use Structured Streaming or streaming tables to consume changes."),
    ("Task", "Databricks Workflows / Jobs", "Replace scheduled tasks with Databricks Jobs using SQL or notebook tasks with cron or interval schedules."),
    ("Pipe", "Auto Loader", "Replace Snowflake pipes with Auto Loader incremental ingestion using cloud storage notifications or directory listing."),
    ("File Format", "Inline Reader Options", "Snowflake file formats have no direct equivalent — specify format options inline in COPY INTO or Auto Loader."),
    ("Masking Policy", "Column Mask / Row Filter", "Map to Databricks column masks or row filters in Unity Catalog."),
    ("Row Access Policy", "Row Filter", "Implement as row filters in Unity Catalog for fine-grained access control."),
    ("Stage", "Volume / External Location + Storage Credential", "Internal stages → Managed Volumes; External stages → Storage Credential + External Location + optional External Volume."),
    ("Sequence", "Identity Column / Sequence", "Use GENERATED BY DEFAULT AS IDENTITY for auto-increment or Databricks SQL Sequences (Preview)."),
    ("Dynamic Table", "Materialized View / Streaming Table", "Snowflake dynamic tables can map to Databricks materialized views or streaming tables depending on refresh mode."),
    ("Alert", "Databricks Alert / Workflow", "Replace Snowflake alerts with Databricks SQL Alerts or scheduled workflow checks."),
    ("Resource Monitor", "Databricks Budget / Policy", "Use Databricks budgets, policies, and cluster policies for resource governance."),
    ("Warehouse", "SQL Warehouse / Cluster", "Map Snowflake warehouses to Databricks SQL Warehouses (Serverless or Pro) or all-purpose clusters."),
    ("External Table", "Unity Catalog External Table", "External tables map directly to Unity Catalog external tables with cloud storage locations."),
    ("Network Policy", "IP ACL / Private Link", "Implement network restrictions via Databricks IP access lists or Private Link."),
    ("Storage Integration", "Storage Credential", "Map to Unity Catalog storage credentials for cloud storage access."),
    ("Share", "Delta Sharing", "Replace Snowflake shares with Delta Sharing for cross-platform data sharing."),
]


def _type_display_name(raw: str) -> str:
    return raw.replace("_", " ").title()


OBJECT_TYPE_LABELS = {}
for _attr_name in dir(ObjectType):
    if _attr_name.startswith("_") or _attr_name == "UNKNOWN":
        continue
    _val = getattr(ObjectType, _attr_name)
    if isinstance(_val, str):
        OBJECT_TYPE_LABELS[_val] = _type_display_name(_val)
OBJECT_TYPE_LABELS[ObjectType.UNKNOWN] = "Unknown"


def _complexity_level(obj, result: ValidationResult = None) -> tuple[str, int]:
    base = {"table": 1, "view": 2, "function": 3, "procedure": 4}.get(obj.object_type, 3)
    feature_count = len(detect_snowflake_features(obj.raw_sql))
    base += feature_count
    if result:
        base += len(result.warnings) * 1
        base += len(result.issues) * 2
        base += len(result.errors) * 3
        if result.status == "ARCHITECTURAL CHANGE":
            base += 2
    if base <= 2:
        return "Easy", base
    elif base <= 4:
        return "Medium", base
    elif base <= 7:
        return "Hard", base
    else:
        return "Expert", base


def _h(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&#39;")


def _build_svg_dep_graph(dep_graph: DependencyGraph) -> str:
    dep_graph.has_cycles()
    ordered = dep_graph.get_deployment_order()
    nodes_by_name: dict[str, dict] = {}
    for obj in ordered:
        n = obj.name.lower()
        deps = dep_graph.edges.get(n, [])
        rev = dep_graph.reverse_edges.get(n, [])
        nodes_by_name[n] = {"name": obj.name, "type": obj.object_type, "deps": deps, "rev": rev}
    if not nodes_by_name:
        return "<p>No dependencies detected.</p>"

    TYPE_ORDER = [
        "schema",
        "table", "external_table", "iceberg_table", "dynamic_table",
        "materialized_view", "view",
        "function",
        "procedure",
        "stream", "task", "pipe", "stage",
    ]
    TYPE_COLORS = {
        "schema":              { "bg": "#eef2ff", "border": "#6366f1", "text": "#4338ca", "badge": "#6366f1", "colbg": "#f4f6ff" },
        "table":               { "bg": "#f0fdf4", "border": "#22c55e", "text": "#15803d", "badge": "#22c55e", "colbg": "#f4fdf6" },
        "external_table":      { "bg": "#f0fdf4", "border": "#22c55e", "text": "#15803d", "badge": "#22c55e", "colbg": "#f4fdf6" },
        "iceberg_table":       { "bg": "#f0fdf4", "border": "#22c55e", "text": "#15803d", "badge": "#22c55e", "colbg": "#f4fdf6" },
        "dynamic_table":       { "bg": "#f0fdf4", "border": "#22c55e", "text": "#15803d", "badge": "#22c55e", "colbg": "#f4fdf6" },
        "materialized_view":   { "bg": "#ecfeff", "border": "#06b6d4", "text": "#0e7490", "badge": "#06b6d4", "colbg": "#f2fdfe" },
        "view":                { "bg": "#ecfeff", "border": "#06b6d4", "text": "#0e7490", "badge": "#06b6d4", "colbg": "#f2fdfe" },
        "function":            { "bg": "#fffbeb", "border": "#f59e0b", "text": "#b45309", "badge": "#f59e0b", "colbg": "#fffdf3" },
        "procedure":           { "bg": "#fef2f2", "border": "#ef4444", "text": "#b91c1c", "badge": "#ef4444", "colbg": "#fef6f6" },
        "stream":              { "bg": "#fdf2f8", "border": "#ec4899", "text": "#be185d", "badge": "#ec4899", "colbg": "#fef6fa" },
        "task":                { "bg": "#f3e8ff", "border": "#8b5cf6", "text": "#6d28d9", "badge": "#8b5cf6", "colbg": "#f8f4ff" },
        "pipe":                { "bg": "#f0fdfa", "border": "#14b8a6", "text": "#0f766e", "badge": "#14b8a6", "colbg": "#f4fdfb" },
        "stage":               { "bg": "#fff7ed", "border": "#f97316", "text": "#c2410c", "badge": "#f97316", "colbg": "#fffbf4" },
    }
    DEFAULT_COLOR = { "bg": "#f8fafc", "border": "#94a3b8", "text": "#475569", "badge": "#94a3b8", "colbg": "#f8f8f8" }

    # Map types to columns
    type_col: dict[str, int] = {}
    col = 0
    for t in TYPE_ORDER:
        if any(info["type"] == t for info in nodes_by_name.values()):
            type_col[t] = col
            col += 1

    column_nodes: dict[int, list[str]] = {}
    for name, info in nodes_by_name.items():
        t = info["type"]
        c = type_col.get(t, -1)
        if c < 0:
            c = max(type_col.values()) + 1 if type_col else 0
            type_col[t] = c
        column_nodes.setdefault(c, []).append(name)

    if not column_nodes:
        return "<p>No dependencies detected.</p>"

    used_cols = sorted(column_nodes.keys())
    total_cols = len(used_cols)

    box_w, box_h = 220, 42
    col_gap = 50
    row_gap = 28
    pad_x = 50
    pad_y = 60
    header_h = 30

    col_width = box_w + col_gap
    max_row = max(len(v) for v in column_nodes.values()) if column_nodes else 1
    total_w = total_cols * col_width + pad_x * 2
    total_h = header_h + max_row * (box_h + row_gap) + pad_y + header_h
    total_w = max(total_w, 750)
    total_h = max(total_h, 300)

    svg_parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {total_w} {total_h}" style="width:100%;height:auto;background:#fff;border-radius:8px;" class="dep-svg">']
    edge_layer: list[str] = []
    node_layer: list[str] = []

    # Column backgrounds
    col_headers: list[str] = []
    for ci, c in enumerate(used_cols):
        cx = pad_x + ci * col_width
        color = DEFAULT_COLOR
        for t in TYPE_ORDER:
            if type_col.get(t) == c:
                color = TYPE_COLORS.get(t, DEFAULT_COLOR)
                break
        col_headers.append(f'<rect x="{cx}" y="{pad_y}" width="{box_w + col_gap}" height="{total_h - pad_y * 2}" fill="{color["colbg"]}" rx="4"/>')

    node_positions: dict[str, tuple[float, float]] = {}
    for ci, c in enumerate(used_cols):
        items = column_nodes[c]
        items.sort(key=lambda n: nodes_by_name[n]["name"])
        x = pad_x + ci * col_width + col_gap / 2
        y_start = pad_y + header_h + (total_h - pad_y - header_h - pad_y - header_h - len(items) * (box_h + row_gap)) / 2 + row_gap / 2
        if y_start < pad_y + header_h + 4:
            y_start = pad_y + header_h + 4
        for i, n in enumerate(items):
            y = y_start + i * (box_h + row_gap)
            cx = x + box_w / 2
            cy = y + box_h / 2
            node_positions[n] = (cx, cy)
            info = nodes_by_name[n]
            color = TYPE_COLORS.get(info["type"], DEFAULT_COLOR)
            node_layer.append(f'<rect x="{x}" y="{y}" width="{box_w}" height="{box_h}" rx="6" fill="{color["bg"]}" stroke="{color["border"]}" stroke-width="1.5"/>')
            node_layer.append(f'<text x="{x + 12}" y="{cy + 1}" font-family="system-ui,sans-serif" font-size="13" fill="{color["text"]}" font-weight="600">{_h(info["name"][:22])}</text>')

    # Column headers
    for ci, c in enumerate(used_cols):
        x = pad_x + ci * col_width + col_gap / 2
        label_c = ""
        type_for_col = None
        for t in TYPE_ORDER:
            if type_col.get(t) == c:
                label_c = OBJECT_TYPE_LABELS.get(t, t)
                type_for_col = t
                break
        if not label_c:
            continue
        color = TYPE_COLORS.get(type_for_col, DEFAULT_COLOR) if type_for_col else DEFAULT_COLOR
        tw = len(label_c) * 9 + 20
        th = 22
        cx = x + box_w / 2
        col_headers.append(f'<rect x="{cx - tw / 2}" y="{pad_y + 4}" width="{tw}" height="{th}" rx="11" fill="{color["badge"]}" opacity="0.9"/>')
        col_headers.append(f'<text x="{cx}" y="{pad_y + 4 + th / 2 + 1}" text-anchor="middle" dominant-baseline="middle" font-family="system-ui,sans-serif" font-size="12" fill="#fff" font-weight="700">{_h(label_c)}</text>')

    svg_parts.extend(col_headers)

    # Arrow defs with glow filter
    arrow_id = f"a_{uuid.uuid4().hex[:6]}"
    filter_id = f"g_{uuid.uuid4().hex[:6]}"
    svg_parts.append(f'<defs><filter id="{filter_id}" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="1.5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><marker id="{arrow_id}" markerWidth="12" markerHeight="8" refX="12" refY="4" orient="auto"><path d="M0,0 L12,4 L0,8 Z" fill="#475569"/></marker></defs>')

    # Draw edges with orthogonal routing
    for n, info in nodes_by_name.items():
        if n not in node_positions:
            continue
        sx, sy = node_positions[n]
        for dep_name in info["deps"]:
            dep_lower = dep_name.lower()
            if dep_lower not in node_positions:
                continue
            dx, dy = node_positions[dep_lower]

            if dx > sx:
                x1 = sx + box_w / 2
                y1 = sy
                x4 = dx - box_w / 2
                y4 = dy
                mx = (x1 + x4) / 2
                path = f"M{x1},{y1} L{mx},{y1} L{mx},{y4} L{x4},{y4}"
            else:
                mx = (sx + dx) / 2
                x1 = sx - box_w / 2
                y1 = sy
                x4 = dx + box_w / 2
                y4 = dy
                path = f"M{x1},{y1} L{mx},{y1} L{mx},{y4} L{x4},{y4}"

            edge_layer.append(f'<path d="{path}" fill="none" stroke="#475569" stroke-width="2.5" stroke-linejoin="round" filter="url(#{filter_id})" marker-end="url(#{arrow_id})"/>')

    svg_parts.extend(edge_layer)
    svg_parts.extend(node_layer)
    svg_parts.append("</svg>")
    return "\n".join(svg_parts)


_CSS = """
:root {
  --bg: #f8fafc;
  --surface: #ffffff;
  --text: #0f172a;
  --text-secondary: #64748b;
  --border: #e2e8f0;
  --primary: #2563eb;
  --primary-light: #eff6ff;
  --success: #22c55e;
  --success-bg: #f0fdf4;
  --warning: #f59e0b;
  --warning-bg: #fffbeb;
  --error: #ef4444;
  --error-bg: #fef2f2;
  --arch: #7c3aed;
  --arch-bg: #f5f3ff;
  --shadow: 0 1px 3px 0 rgba(0,0,0,0.06), 0 1px 2px -1px rgba(0,0,0,0.06);
  --shadow-lg: 0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -2px rgba(0,0,0,0.05);
  --radius: 8px;
  --radius-lg: 12px;
  --font: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
  --mono: 'SF Mono', 'Monaco', 'Menlo', 'Consolas', monospace;
  --nav-h: 56px;
  --max-width: 1200px;
}
.dark {
  --bg: #0f172a;
  --surface: #1e293b;
  --text: #f1f5f9;
  --text-secondary: #94a3b8;
  --border: #334155;
  --primary-light: #1e3a5f;
  --success-bg: #052e16;
  --warning-bg: #422006;
  --error-bg: #450a0a;
  --arch-bg: #2e1065;
  --shadow: 0 1px 3px 0 rgba(0,0,0,0.3);
  --shadow-lg: 0 4px 6px -1px rgba(0,0,0,0.4);
}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html{scroll-behavior:smooth;font-size:16px}
body{font-family:var(--font);background:var(--bg);color:var(--text);line-height:1.6;-webkit-font-smoothing:antialiased}
a{color:var(--primary);text-decoration:none}
.layout{max-width:var(--max-width);margin:0 auto;padding:0 24px 48px}
/* Sticky Header */
.report-header{position:sticky;top:0;z-index:100;background:var(--surface);border-bottom:1px solid var(--border);padding:12px 0;box-shadow:var(--shadow)}
.report-header .layout{display:flex;align-items:center;justify-content:space-between;gap:16px;padding-top:0;padding-bottom:0}
.header-left h1{font-size:18px;font-weight:700;letter-spacing:-0.3px}
.header-left .meta{font-size:12px;color:var(--text-secondary);margin-top:2px}
.header-actions{display:flex;gap:8px;flex-wrap:wrap}
.btn{display:inline-flex;align-items:center;gap:6px;padding:7px 14px;border-radius:6px;font-size:13px;font-weight:500;border:1px solid var(--border);background:var(--surface);color:var(--text);cursor:pointer;transition:all .15s;white-space:nowrap;font-family:var(--font)}
.btn:hover{background:var(--bg);border-color:var(--primary);color:var(--primary)}
.btn-primary{background:var(--primary);color:#fff;border-color:var(--primary)}
.btn-primary:hover{filter:brightness(1.1);background:var(--primary)}
/* KPI Cards */
.kpi-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px;margin-bottom:32px}
.kpi-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);padding:24px;box-shadow:var(--shadow);position:relative}
.kpi-card .kpi-label{font-size:12px;font-weight:600;color:var(--text-secondary);text-transform:uppercase;letter-spacing:0.2px;margin-bottom:10px;overflow-wrap:break-word}
.kpi-card .kpi-value{font-size:32px;font-weight:700;line-height:1.1;letter-spacing:-0.5px;word-break:break-word}
.kpi-card .kpi-sub{font-size:12px;color:var(--text-secondary);margin-top:4px}
.kpi-card .kpi-ring{position:absolute;top:12px;right:12px}
.kpi-pass .kpi-value{color:var(--success)}
.kpi-warn .kpi-value{color:var(--warning)}
.kpi-error .kpi-value{color:var(--error)}
.kpi-arch .kpi-value{color:var(--arch)}
.kpi-score .kpi-value{color:var(--primary)}
/* Section */
.section{margin-bottom:40px}
.section-title{font-size:20px;font-weight:700;margin-bottom:16px;letter-spacing:-0.3px;display:flex;align-items:center;gap:8px}
.section-title .count-badge{font-size:12px;font-weight:600;padding:2px 10px;border-radius:999px;background:var(--border);color:var(--text-secondary)}
/* Cards */
.card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);box-shadow:var(--shadow);overflow:hidden}
.card-header{padding:16px 20px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;cursor:pointer;user-select:none}
.card-header:hover{background:var(--bg)}
.card-header h3{font-size:15px;font-weight:600}
.card-body{padding:20px}
/* Type Group Cards */
.type-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}
.type-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:16px;box-shadow:var(--shadow)}
.type-card .type-name{font-size:14px;font-weight:600;margin-bottom:8px}
.type-card .type-stats{display:flex;gap:10px;font-size:12px;color:var(--text-secondary)}
.type-card .type-stats span{display:flex;align-items:center;gap:3px}
.type-card .type-bar{height:4px;border-radius:2px;background:var(--border);margin-top:10px;overflow:hidden}
.type-card .type-bar-fill{height:100%;border-radius:2px;transition:width .5s}
/* Progress Bars */
.progress-list{display:flex;flex-direction:column;gap:8px}
.progress-item{display:flex;align-items:center;gap:12px}
.progress-item .plabel{font-size:13px;font-weight:500;width:120px;flex-shrink:0}
.progress-item .pbar{flex:1;height:8px;border-radius:4px;background:var(--border);overflow:hidden}
.progress-item .pbar-fill{height:100%;border-radius:4px;transition:width .6s;background:var(--primary)}
.progress-item .ppct{font-size:13px;font-weight:600;width:48px;text-align:right;color:var(--text-secondary)}
/* Arch Mapping */
.arch-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:12px}
.arch-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:16px;box-shadow:var(--shadow)}
.arch-card .arch-src{font-weight:600;font-size:14px;color:var(--text)}
.arch-card .arch-arrow{font-size:13px;color:var(--text-secondary);margin:4px 0}
.arch-card .arch-dst{font-weight:500;font-size:13px;color:var(--primary)}
.arch-card .arch-note{font-size:12px;color:var(--text-secondary);margin-top:6px;line-height:1.5}
/* Table */
.table-wrap{overflow-x:auto}
table{width:100%;border-collapse:collapse;font-size:13px}
thead{background:var(--bg);position:sticky;top:var(--nav-h);z-index:10}
th{padding:10px 12px;text-align:left;font-weight:600;color:var(--text-secondary);font-size:12px;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid var(--border);cursor:pointer;white-space:nowrap;user-select:none}
th:hover{color:var(--text)}
th .sort-icon{opacity:.4;margin-left:4px}
td{padding:10px 12px;border-bottom:1px solid var(--border);vertical-align:middle}
tr:hover td{background:var(--bg)}
/* Status badges */
.badge{display:inline-flex;align-items:center;gap:4px;padding:3px 10px;border-radius:999px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.3px}
.badge-pass{background:var(--success-bg);color:var(--success)}
.badge-warning{background:var(--warning-bg);color:var(--warning)}
.badge-error{background:var(--error-bg);color:var(--error)}
.badge-arch{background:var(--arch-bg);color:var(--arch)}
.badge-issue{background:#f0f9ff;color:#0284c7}
/* SQL block */
.sql-block{position:relative;margin:12px 0;border:1px solid var(--border);border-radius:var(--radius);overflow:hidden}
.sql-block .sql-header{display:flex;align-items:center;justify-content:space-between;padding:8px 12px;background:var(--bg);border-bottom:1px solid var(--border);font-size:12px;font-weight:500;color:var(--text-secondary)}
.sql-block .sql-header .copy-btn{background:var(--surface);border:1px solid var(--border);padding:4px 10px;font-size:11px;border-radius:4px;cursor:pointer;color:var(--text-secondary);font-family:var(--font)}
.sql-block .sql-header .copy-btn:hover{color:var(--primary);border-color:var(--primary)}
.sql-block pre{overflow-x:auto;padding:12px;margin:0;font-family:var(--mono);font-size:12px;line-height:1.7;background:var(--surface);color:var(--text);tab-size:2;-moz-tab-size:2}
.sql-block pre code{font-family:inherit}
/* SQL syntax highlighting */
.sql-kw{color:#2563eb;font-weight:600}
.sql-str{color:#059669}
.sql-num{color:#d97706}
.sql-cmt{color:#94a3b8;font-style:italic}
.sql-op{color:#7c3aed}
.sql-fn{color:#0891b2}
.sql-type{color:#dc2626}
/* Collapsible object details */
.detail-card{margin-bottom:12px;border:1px solid var(--border);border-radius:var(--radius-lg);overflow:hidden;background:var(--surface);box-shadow:var(--shadow)}
.detail-card summary{display:flex;align-items:center;padding:14px 20px;cursor:pointer;user-select:none;gap:12px;list-style:none}
.detail-card summary::-webkit-details-marker{display:none}
.detail-card summary:hover{background:var(--bg)}
.detail-card summary .dc-status{flex-shrink:0}
.detail-card summary .dc-name{font-weight:600;font-size:14px;flex:1}
.detail-card summary .dc-meta{font-size:12px;color:var(--text-secondary);display:flex;gap:12px}
.detail-card[open] summary{border-bottom:1px solid var(--border)}
.detail-body{padding:20px}
.sql-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px}
@media(max-width:800px){.sql-columns{grid-template-columns:1fr}}
/* Validation checks */
.val-checks{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px;padding-top:12px;border-top:1px solid var(--border)}
.val-check{display:flex;align-items:center;gap:5px;font-size:12px;color:var(--text-secondary);padding:4px 10px;border-radius:999px;background:var(--bg)}
.val-check.ok{color:var(--success)}
/* Dep Graph SVG */
.dep-svg{background:var(--surface);border-radius:var(--radius-lg);border:1px solid var(--border)}
.dark .dep-svg rect{fill:#1e293b!important;stroke:#334155!important}
.dark .dep-svg text{fill:#f1f5f9!important}
.dark .dep-svg line{stroke:#475569!important}
.dark .dep-svg path{fill:#475569!important}
/* Issue cards */
.issue-list{display:flex;flex-direction:column;gap:8px}
.issue-card{display:flex;gap:12px;padding:12px 16px;border:1px solid var(--border);border-radius:var(--radius);background:var(--surface)}
.issue-card .sev{flex-shrink:0;width:6px;border-radius:3px;align-self:stretch}
.issue-card .sev-error{background:var(--error)}
.issue-card .sev-warning{background:var(--warning)}
.issue-card .sev-arch{background:var(--arch)}
.issue-card .sev-issue{background:#0284c7}
.issue-card .ic-body{flex:1;min-width:0}
.issue-card .ic-obj{font-weight:600;font-size:13px}
.issue-card .ic-msg{font-size:12px;color:var(--text-secondary);margin-top:2px}
/* Summary card */
.summary-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);padding:32px;text-align:center;box-shadow:var(--shadow-lg)}
.summary-card .score-ring{margin:0 auto 16px}
.summary-card .score-value{font-size:48px;font-weight:800;letter-spacing:-1px}
.summary-card .score-label{font-size:14px;color:var(--text-secondary);margin-top:4px}
.summary-card .rec{margin-top:20px;padding:16px;border-radius:var(--radius);background:var(--bg);font-size:14px;text-align:left}
.summary-card .rec h4{font-weight:600;margin-bottom:6px}
.summary-card .rec ul{list-style:none;padding:0}
.summary-card .rec ul li{padding:3px 0;font-size:13px;color:var(--text-secondary)}
.summary-card .rec ul li::before{content:"• ";color:var(--primary)}
/* Search */
.search-bar{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}
.search-bar input{flex:1;min-width:200px;padding:9px 14px;border:1px solid var(--border);border-radius:6px;font-size:13px;background:var(--surface);color:var(--text);font-family:var(--font)}
.search-bar input:focus{outline:none;border-color:var(--primary);box-shadow:0 0 0 3px rgba(37,99,235,0.15)}
.search-bar select{padding:9px 14px;border:1px solid var(--border);border-radius:6px;font-size:13px;background:var(--surface);color:var(--text);font-family:var(--font)}
.search-bar select:focus{outline:none;border-color:var(--primary)}
/* No results */
.no-results{text-align:center;padding:48px 24px;color:var(--text-secondary);font-size:14px}
/* Print */
@media print{
  .report-header{position:static;box-shadow:none}
  .btn,.header-actions .btn{display:none}
  .detail-card[open] summary{border-bottom:0}
  .detail-card .sql-columns{display:block}
  .detail-card .sql-block{break-inside:avoid;page-break-inside:avoid}
  .dark body{background:#fff;color:#000}
  .no-print{display:none!important}
  .section{margin-bottom:24px}
  body{font-size:11px}
  .kpi-card .kpi-value{font-size:24px}
}
"""

_JS = """
(function(){
const data = JSON.parse(document.getElementById('report-data').textContent);
const STORAGE_KEY = 'migration-report-dark';
let darkMode = localStorage.getItem(STORAGE_KEY) === 'true';
let expandedAll = false;

function init(){
  initDarkMode();
  initSearch();
  initSort();
  initCopyButtons();
  initExpandCollapse();
  initNavScroll();
  highlightSQL();
}
function initDarkMode(){
  const toggle = document.getElementById('dark-toggle');
  if(!toggle) return;
  if(darkMode) document.documentElement.classList.add('dark');
  toggle.addEventListener('click', function(){
    darkMode = !darkMode;
    document.documentElement.classList.toggle('dark', darkMode);
    localStorage.setItem(STORAGE_KEY, darkMode);
  });
}
function initSearch(){
  const input = document.getElementById('search-input');
  const filter = document.getElementById('status-filter');
  if(!input) return;
  function filterRows(){
    const q = input.value.toLowerCase().trim();
    const sf = filter ? filter.value : 'all';
    const rows = document.querySelectorAll('#object-table tbody tr');
    let visible = 0;
    for(const row of rows){
      const name = (row.dataset.name||'').toLowerCase();
      const status = row.dataset.status||'';
      const matchSearch = !q || name.includes(q);
      const matchFilter = sf === 'all' || status === sf;
      const show = matchSearch && matchFilter;
      row.style.display = show ? '' : 'none';
      if(show) visible++;
    }
    const noResults = document.getElementById('no-results');
    if(noResults) noResults.style.display = visible === 0 ? '' : 'none';
  }
  input.addEventListener('input', filterRows);
  if(filter) filter.addEventListener('change', filterRows);
}
function initSort(){
  const table = document.getElementById('object-table');
  if(!table) return;
  const ths = table.querySelectorAll('th[data-col]');
  let sortCol = -1, sortAsc = true;
  function sortTable(colIdx){
    const tbody = table.querySelector('tbody');
    const rows = Array.from(tbody.querySelectorAll('tr'));
    rows.sort(function(a,b){
      const va = a.children[colIdx]?.textContent?.trim().toLowerCase()||'';
      const vb = b.children[colIdx]?.textContent?.trim().toLowerCase()||'';
      if(va < vb) return sortAsc ? -1 : 1;
      if(va > vb) return sortAsc ? 1 : -1;
      return 0;
    });
    for(const r of rows) tbody.appendChild(r);
    for(const th of ths){
      const icon = th.querySelector('.sort-icon');
      if(icon) icon.textContent = th.dataset.col == colIdx ? (sortAsc ? '\\25B2' : '\\25BC') : '\\25B4\\25BE';
    }
  }
  for(const th of ths){
    th.addEventListener('click', function(){
      const col = parseInt(this.dataset.col);
      if(sortCol === col) sortAsc = !sortAsc;
      else { sortCol = col; sortAsc = true; }
      sortTable(col);
    });
  }
}
function initCopyButtons(){
  for(const btn of document.querySelectorAll('.copy-btn')){
    btn.addEventListener('click', function(){
      const code = this.closest('.sql-block').querySelector('code');
      if(!code) return;
      const text = code.textContent;
      navigator.clipboard.writeText(text).then(function(){
        const orig = this.textContent;
        this.textContent = 'Copied!';
        setTimeout(() => { this.textContent = orig; }, 1500);
      }.bind(this));
    });
  }
}
function initExpandCollapse(){
  const expandBtn = document.getElementById('expand-all');
  const collapseBtn = document.getElementById('collapse-all');
  if(!expandBtn || !collapseBtn) return;
  function toggleAll(open){
    for(const detail of document.querySelectorAll('.detail-card')){
      detail.open = open;
    }
  }
  expandBtn.addEventListener('click', function(){ toggleAll(true); });
  collapseBtn.addEventListener('click', function(){ toggleAll(false); });
}
function initNavScroll(){
  const links = document.querySelectorAll('.nav-link');
  if(!links.length) return;
  const observer = new IntersectionObserver(function(entries){
    for(const entry of entries){
      if(entry.isIntersecting){
        const id = entry.target.id;
        for(const link of links){
          link.classList.toggle('active', link.getAttribute('href') === '#' + id);
        }
      }
    }
  }, { rootMargin: '-100px 0px -60% 0px' });
  for(const section of document.querySelectorAll('.section[id]')){
    observer.observe(section);
  }
}
function highlightSQL(){
  for(const code of document.querySelectorAll('.sql-block code')){
    if(code.querySelector('span')) continue;
    let html = code.textContent;
    html = html.replace(/\\b(BEGIN|CASE|WHEN|THEN|ELSE|END|IF|ELSEIF|LOOP|WHILE|FOR|DO|DECLARE|SET|GET|DIAGNOSTICS|ROW_COUNT|RETURN|SELECT|FROM|WHERE|AND|OR|NOT|IN|IS|NULL|LIKE|BETWEEN|EXISTS|UNION|ALL|INTERSECT|MINUS|AS|ON|JOIN|LEFT|RIGHT|INNER|OUTER|FULL|CROSS|NATURAL|USING|GROUP|BY|ORDER|ASC|DESC|HAVING|LIMIT|OFFSET|FETCH|NEXT|ROWS|ONLY|WITH|RECURSIVE|CREATE|OR|REPLACE|TABLE|VIEW|FUNCTION|PROCEDURE|STREAM|TASK|PIPE|STAGE|FILE|FORMAT|ALERT|MASKING|POLICY|ROW|ACCESS|SEQUENCE|DYNAMIC|MATERIALIZED|EXTERNAL|SCHEMA|DATABASE|CATALOG|WORKSPACE|TAG|TAGS|ALTER|DROP|INSERT|INTO|VALUES|UPDATE|DELETE|MERGE|TRUNCATE|COPY|INTO|GRANT|REVOKE|SHOW|DESCRIBE|USE|COMMIT|ROLLBACK|BEGIN|CALL|EXECUTE|IMMEDIATE|LANGUAGE|SQL|SECURITY|INVOKER|DEFINER|RETURNS|COMMENT|CLAUSE|TBLPROPERTIES|USING|IDENTITY|GENERATED|BY|DEFAULT|ALWAYS|PRIMARY|KEY|FOREIGN|REFERENCES|CONSTRAINT|UNIQUE|CHECK|INDEX|CLUSTER|SORT|ZORDER|OPTIMIZE|VACUUM|ANALYZE|EXPLAIN|CACHE|UNCACHE|REFRESH|INVALIDATE|METADATA)\\b/gi, '<span class="sql-kw">$1</span>');
    html = html.replace(/\\b(STRING|INT|INTEGER|BIGINT|SMALLINT|TINYINT|BOOLEAN|DATE|TIMESTAMP|TIMESTAMP_NTZ|TIMESTAMP_LTZ|TIMESTAMP_TZ|DECIMAL|NUMERIC|NUMBER|FLOAT|DOUBLE|REAL|BINARY|VARBINARY|BYTES|ARRAY|STRUCT|MAP|VARIANT|OBJECT|GEOGRAPHY|GEOMETRY|INTERVAL)\\b/gi, '<span class="sql-type">$1</span>');
    html = html.replace(/\\b(COUNT|SUM|AVG|MIN|MAX|COALESCE|NULLIF|CAST|TRY_CAST|CONVERT|CURRENT_DATE|CURRENT_TIMESTAMP|CURRENT_TIME|DATEADD|DATEDIFF|DATETRUNC|EXTRACT|YEAR|MONTH|DAY|HOUR|MINUTE|SECOND|UPPER|LOWER|TRIM|LTRIM|RTRIM|SUBSTRING|SUBSTR|LEFT|RIGHT|LENGTH|REPLACE|REGEXP_REPLACE|REGEXP_EXTRACT|REGEXP_LIKE|SPLIT|CONCAT|CONCAT_WS|ARRAY_AG|LISTAG|COLLECT_LIST|COLLECT_SET|ROW_NUMBER|RANK|DENSE_RANK|LAG|LEAD|FIRST_VALUE|LAST_VALUE|NTH_VALUE|NTILE|PERCENTILE|CUME_DIST|RANDOM|RAND|FLOOR|CEIL|CEILING|ROUND|ABS|MOD|POWER|SQRT|EXP|LN|LOG|GREATEST|LEAST|TO_DATE|TO_TIMESTAMP|TO_CHAR|TO_VARCHAR|TO_NUMBER|TO_DECIMAL|PARSE_JSON|TRY_PARSE_JSON|FROM_JSON|TO_JSON|JSON_EXTRACT_PATH_TEXT|JSON_KEYS|OBJECT_KEYS|FLATTEN|LATERAL|VIEW|EXPLODE|POSEXPLODE|TRANSFORM|FILTER|REDUCE|ZIP_WITH|MAP_FROM_ARRAYS|MAP_KEYS|MAP_VALUES|TYPEOF)\\b/gi, '<span class="sql-fn">$1</span>');
    html = html.replace(/(--[^\\n]*)/g, '<span class="sql-cmt">$1</span>');
    html = html.replace(/'[^']*'/g, '<span class="sql-str">$&</span>');
    html = html.replace(/\\b(\\d+\\.\\d+|\\d+)\\b/g, '<span class="sql-num">$1</span>');
    html = html.replace(/([=<>!]=?|\\|\\||&&|::)/g, '<span class="sql-op">$1</span>');
    code.innerHTML = html;
  }
}
document.addEventListener('DOMContentLoaded', init);
})();
"""


_SQL_STYLES = {
    'sql-kw': 'color:#2563eb;font-weight:600',
    'sql-type': 'color:#dc2626',
    'sql-fn': 'color:#0891b2',
    'sql-str': 'color:#059669',
    'sql-num': 'color:#d97706',
    'sql-cmt': 'color:#94a3b8;font-style:italic',
    'sql-op': 'color:#7c3aed',
}

def _highlight_sql_text(sql: str) -> str:
    """Server-side SQL syntax highlighting with inline styles (no CSS dependency)."""
    if not sql:
        return ""
    import re

    def _esc(text: str) -> str:
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&#39;")

    mapping: dict[str, str] = {}
    counter = 0

    def _ph() -> str:
        nonlocal counter
        k = "\x01\x02" + "\x03" * (counter + 1) + "\x02\x01"
        counter += 1
        return k

    def _set(m, cls: str) -> str:
        k = _ph()
        style = _SQL_STYLES.get(cls, '')
        mapping[k] = f'<span style="{style}">{_esc(m.group(1))}</span>'
        return k

    html = sql

    html = re.sub(r'\b(BEGIN|CASE|WHEN|THEN|ELSE|END|IF|ELSEIF|LOOP|WHILE|FOR|DO|DECLARE|SET|GET|DIAGNOSTICS|ROW_COUNT|RETURN|SELECT|FROM|WHERE|AND|OR|NOT|IN|IS|NULL|LIKE|BETWEEN|EXISTS|UNION|ALL|INTERSECT|MINUS|AS|ON|JOIN|LEFT|RIGHT|INNER|OUTER|FULL|CROSS|NATURAL|USING|GROUP|BY|ORDER|ASC|DESC|HAVING|LIMIT|OFFSET|FETCH|NEXT|ROWS|ONLY|WITH|RECURSIVE|CREATE|OR|REPLACE|TABLE|VIEW|FUNCTION|PROCEDURE|STREAM|TASK|PIPE|STAGE|FILE|FORMAT|ALERT|MASKING|POLICY|ROW|ACCESS|SEQUENCE|DYNAMIC|MATERIALIZED|EXTERNAL|SCHEMA|DATABASE|CATALOG|WORKSPACE|TAG|TAGS|ALTER|DROP|INSERT|INTO|VALUES|UPDATE|DELETE|MERGE|TRUNCATE|COPY|INTO|GRANT|REVOKE|SHOW|DESCRIBE|USE|COMMIT|ROLLBACK|BEGIN|CALL|EXECUTE|IMMEDIATE|LANGUAGE|SQL|SECURITY|INVOKER|DEFINER|RETURNS|COMMENT|CLAUSE|TBLPROPERTIES|USING|IDENTITY|GENERATED|BY|DEFAULT|ALWAYS|PRIMARY|KEY|FOREIGN|REFERENCES|CONSTRAINT|UNIQUE|CHECK|INDEX|CLUSTER|SORT|ZORDER|OPTIMIZE|VACUUM|ANALYZE|EXPLAIN|CACHE|UNCACHE|REFRESH|INVALIDATE|METADATA)\b', lambda m: _set(m, 'sql-kw'), html, flags=re.IGNORECASE)
    html = re.sub(r'\b(STRING|INT|INTEGER|BIGINT|SMALLINT|TINYINT|BOOLEAN|DATE|TIMESTAMP|TIMESTAMP_NTZ|TIMESTAMP_LTZ|TIMESTAMP_TZ|DECIMAL|NUMERIC|NUMBER|FLOAT|DOUBLE|REAL|BINARY|VARBINARY|BYTES|ARRAY|STRUCT|MAP|VARIANT|OBJECT|GEOGRAPHY|GEOMETRY|INTERVAL)\b', lambda m: _set(m, 'sql-type'), html, flags=re.IGNORECASE)
    html = re.sub(r'\b(COUNT|SUM|AVG|MIN|MAX|COALESCE|NULLIF|CAST|TRY_CAST|CONVERT|CURRENT_DATE|CURRENT_TIMESTAMP|CURRENT_TIME|DATEADD|DATEDIFF|DATETRUNC|EXTRACT|YEAR|MONTH|DAY|HOUR|MINUTE|SECOND|UPPER|LOWER|TRIM|LTRIM|RTRIM|SUBSTRING|SUBSTR|LEFT|RIGHT|LENGTH|REPLACE|REGEXP_REPLACE|REGEXP_EXTRACT|REGEXP_LIKE|SPLIT|CONCAT|CONCAT_WS|ARRAY_AG|LISTAG|COLLECT_LIST|COLLECT_SET|ROW_NUMBER|RANK|DENSE_RANK|LAG|LEAD|FIRST_VALUE|LAST_VALUE|NTH_VALUE|NTILE|PERCENTILE|CUME_DIST|RANDOM|RAND|FLOOR|CEIL|CEILING|ROUND|ABS|MOD|POWER|SQRT|EXP|LN|LOG|GREATEST|LEAST|TO_DATE|TO_TIMESTAMP|TO_CHAR|TO_VARCHAR|TO_NUMBER|TO_DECIMAL|PARSE_JSON|TRY_PARSE_JSON|FROM_JSON|TO_JSON|JSON_EXTRACT_PATH_TEXT|JSON_KEYS|OBJECT_KEYS|FLATTEN|LATERAL|VIEW|EXPLODE|POSEXPLODE|TRANSFORM|FILTER|REDUCE|ZIP_WITH|MAP_FROM_ARRAYS|MAP_KEYS|MAP_VALUES|TYPEOF)\b', lambda m: _set(m, 'sql-fn'), html, flags=re.IGNORECASE)
    html = re.sub(r'(--[^\n]*)', lambda m: _set(m, 'sql-cmt'), html)
    html = re.sub(r"('[^']*')", lambda m: _set(m, 'sql-str'), html)
    html = re.sub(r'\b(\d+\.\d+|\d+)\b', lambda m: _set(m, 'sql-num'), html)
    html = re.sub(r'([=<>!]=?|\|\||&&|::)', lambda m: _set(m, 'sql-op'), html)

    html = _esc(html)
    for key, span in reversed(list(mapping.items())):
        html = html.replace(key, span)
    return html


def _build_html(
    summary: dict,
    inventory: ProjectInventory,
    ordered: list,
    validation_results: dict,
    dep_graph: DependencyGraph,
    val_summary: dict,
    auto_conv: int,
    info_warning_count: int,
    manual_review: int,
    architectural_count: int,
    issues_count: int,
    failed: int,
    auto_pct: float,
    info_pct: float,
    manual_review_pct: float,
    arch_pct: float,
    issues_pct: float,
    failed_pct: float,
    complexity_buckets: dict,
    avg_complexity: float,
    norm_score: int,
    type_items: list,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    report_id = uuid.uuid4().hex[:12]
    project_name = _h(summary.get("project", "Migration Project"))
    total_objects = len(inventory.all_objects)
    arch_obj_list = [o for o in ordered if validation_results.get(o.name) and validation_results[o.name].status == "ARCHITECTURAL CHANGE"]

    # Object inventory by type with stats
    type_stats = {}
    for obj in inventory.all_objects:
        t = obj.object_type
        if t not in type_stats:
            type_stats[t] = {"total": 0, "passed": 0, "warnings": 0, "errors": 0}
        type_stats[t]["total"] += 1
        r = validation_results.get(obj.name)
        if r:
            if r.is_pass():
                type_stats[t]["passed"] += 1
            if r.warnings:
                type_stats[t]["warnings"] += 1
            if r.errors:
                type_stats[t]["errors"] += 1
            if r.status == "ERROR":
                type_stats[t]["errors"] += 1

    # Progress bars per type group
    type_groups = {
        "Tables": ["table"],
        "Views": ["view", "materialized_view", "dynamic_table"],
        "Functions": ["function"],
        "Procedures": ["procedure"],
        "Streams": ["stream"],
        "Tasks": ["task"],
        "Pipes": ["pipe"],
        "Stages": ["stage"],
        "File Formats": ["file_format"],
        "Policies": ["masking_policy", "row_access_policy"],
        "Sequences": ["sequence"],
        "Other": [],
    }
    progress_data = []
    seen_types_progress = set()
    for label, type_list in type_groups.items():
        objects_in_group = [o for o in inventory.all_objects if o.object_type in type_list]
        seen_types_progress.update(type_list)
        if not objects_in_group:
            continue
        total = len(objects_in_group)
        passed = sum(1 for o in objects_in_group if validation_results.get(o.name) and validation_results[o.name].status in ("PASS", "WARNING"))
        pct = round(passed / max(total, 1) * 100)
        progress_data.append((label, pct))
    remaining = [o for o in inventory.all_objects if o.object_type not in seen_types_progress]
    if remaining:
        progress_data.append(("Other", round(sum(1 for o in remaining if validation_results.get(o.name) and validation_results[o.name].status in ("PASS", "WARNING")) / max(len(remaining), 1) * 100)))

    # Build object table rows
    table_rows = []
    for obj in ordered:
        r = validation_results.get(obj.name)
        if not r:
            continue
        status = r.status
        status_class = {"PASS": "pass", "WARNING": "warning", "ERROR": "error", "ARCHITECTURAL CHANGE": "arch", "ISSUE": "issue"}.get(status, "warning")
        confidence_pct = round(r.confidence * 100)
        obj_type_label = OBJECT_TYPE_LABELS.get(obj.object_type, obj.object_type)
        review_needed = "Yes" if (obj.converted_sql and "MANUAL REVIEW" in obj.converted_sql) else "No"
        table_rows.append(f"""<tr data-name="{_h(obj.name.lower())}" data-status="{status}">
<td><span class="badge badge-{status_class}">{_h(status)}</span></td>
<td>{_h(obj.name)}</td>
<td>{_h(obj_type_label)}</td>
<td>{confidence_pct}%</td>
<td>{review_needed}</td>
<td>{"" if not r.warnings and not r.issues and not r.errors else "Attention"}</td>
<td>{_h(str(obj.file_path))}</td>
</tr>""")

    # Object detail cards
    detail_cards = []
    type_groups_detail = {}
    for obj in ordered:
        t = obj.object_type
        type_groups_detail.setdefault(t, []).append(obj)
    for t, objs in sorted(type_groups_detail.items()):
        label = OBJECT_TYPE_LABELS.get(t, t)
        cards = []
        for obj in objs:
            r = validation_results.get(obj.name)
            status = r.status if r else "UNKNOWN"
            status_class = {"PASS": "pass", "WARNING": "warning", "ERROR": "error", "ARCHITECTURAL CHANGE": "arch", "ISSUE": "issue"}.get(status, "warning")
            confidence_pct = round(r.confidence * 100) if r else 0
            warnings_html = ""
            for w in (r.warnings if r else []):
                warnings_html += f'<div class="val-check" style="color:var(--warning)">\u26A0 {_h(w)}</div>'
            issues_html = ""
            for iss in (r.issues if r else []):
                issues_html += f'<div class="val-check" style="color:#0284c7">\u2716 {_h(iss)}</div>'
            errors_html = ""
            for e in (r.errors if r else []):
                errors_html += f'<div class="val-check" style="color:var(--error)">\u2716 {_h(e)}</div>'
            deps = dep_graph.edges.get(obj.name.lower(), [])
            deps_html = ", ".join(_h(d) for d in deps) if deps else "<em>none</em>"
            raw_sql = _highlight_sql_text(obj.raw_sql or "")
            conv_sql = _highlight_sql_text(obj.converted_sql or "")
            cards.append(f"""<details class="detail-card">
<summary>
  <span class="badge badge-{status_class}">{_h(status)}</span>
  <span class="dc-name">{_h(obj.name)}</span>
  <span class="dc-meta">
    <span>{_h(label)}</span>
    <span>{confidence_pct}% confidence</span>
  </span>
</summary>
<div class="detail-body">
  <div class="sql-columns">
    <div class="sql-block">
      <div class="sql-header"><span>Original (Snowflake)</span><button class="copy-btn">Copy</button></div>
      <pre><code>{raw_sql}</code></pre>
    </div>
    <div class="sql-block">
      <div class="sql-header"><span>Converted (Databricks)</span><button class="copy-btn">Copy</button></div>
      <pre><code>{conv_sql}</code></pre>
    </div>
  </div>
  <div class="val-checks">
    <div class="val-check ok">\u2713 Parsed</div>
    <div class="val-check ok">\u2713 Converted</div>
    <div class="val-check ok">\u2713 Databricks Compatible</div>
    <div class="val-check ok">\u2713 Dependency Checked</div>
    <div class="val-check ok">\u2713 Review Complete</div>
    {warnings_html}{issues_html}{errors_html}
  </div>
</div>
</details>""")
        if cards:
            detail_cards.append((label, "\n".join(cards)))

    # Issues
    issue_cards = []
    for obj in ordered:
        r = validation_results.get(obj.name)
        if not r:
            continue
        for e in r.errors:
            sev = "error"
            issue_cards.append((sev, _h(obj.name), _h(e)))
        for iss in r.issues:
            sev = "issue"
            issue_cards.append((sev, _h(obj.name), _h(iss)))
        for w in r.warnings:
            if "PRIMARY KEY" in w or "FOREIGN KEY" in w or "VARIANT" in w or "SECURE VIEW" in w:
                continue
            sev = "warning"
            issue_cards.append((sev, _h(obj.name), _h(w)))
        if obj.converted_sql and "MANUAL REVIEW" in obj.converted_sql:
            issue_cards.append(("arch", _h(obj.name), "Manual review required — architectural change"))

    # SVG dependency graph
    svg_dep = _build_svg_dep_graph(dep_graph)

    # Recommendation
    rec_types = []
    for t, count in type_items:
        if count > 0:
            rec_types.append(f"{count} {t}")

    # Navigation items
    nav_items = [
        ("dashboard", "Dashboard"),
        ("inventory", "Inventory"),
        ("summary", "Summary"),
        ("arch-mapping", "Architecture"),
        ("objects", "Objects"),
        ("dependencies", "Dependencies"),
        ("issues", "Issues"),
    ]

    parts = []
    def w(s=""):
        parts.append(s)

    # ── Build HTML ──────────────────────────────────────────────
    w("<!DOCTYPE html>")
    w('<html lang="en">')
    w("<head>")
    w('<meta charset="UTF-8">')
    w('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    w(f"<title>Migration Report — {_h(project_name[:60])}</title>")
    w(f"<style>{_CSS}</style>")
    w("</head>")
    w("<body>")

    # Sticky Header
    w('<div class="report-header">')
    w('<div class="layout">')
    w('<div class="header-left">')
    w(f'<h1>Snowflake &rarr; Databricks &middot; Migration Report</h1>')
    w(f'<div class="meta">{_h(project_name)} &middot; {now} &middot; v{REPORT_VERSION} &middot; Report ID: {report_id}</div>')
    w("</div>")
    w('<div class="header-actions">')
    w('<button class="btn" onclick="window.print()">Print</button>')
    w('<button class="btn" id="expand-all">Expand All</button>')
    w('<button class="btn" id="collapse-all">Collapse All</button>')
    w('<button class="btn" id="dark-toggle">Dark Mode</button>')
    w("</div>")
    w("</div>")
    w("</div>")

    w('<div class="layout">')

    # Navigation
    w('<nav style="display:flex;gap:4px;padding:16px 0 8px;flex-wrap:wrap;position:sticky;top:56px;z-index:90;background:var(--bg);padding-bottom:8px" class="no-print">')
    for nid, nlabel in nav_items:
        w(f'<a href="#{nid}" class="btn nav-link" style="font-size:12px;padding:5px 12px">{_h(nlabel)}</a>')
    w("</nav>")

    # ── 1. Executive Dashboard ──
    w(f'<div class="section" id="dashboard">')
    w('<h2 class="section-title">Executive Dashboard</h2>')
    w('<div class="kpi-grid">')
    # KPI: Total
    total_passing = auto_conv + manual_review
    w(f'<div class="kpi-card kpi-pass"><div class="kpi-label">Total Objects</div><div class="kpi-value">{total_objects}</div><div class="kpi-sub">{total_passing}/{total_objects} processed</div></div>')
    # KPI: Automatically Converted
    w(f'<div class="kpi-card kpi-pass"><div class="kpi-label">Automatically Converted</div><div class="kpi-value">{auto_conv}</div><div class="kpi-sub">{auto_pct:.0f}% of total</div></div>')
    # KPI: Architectural Changes
    w(f'<div class="kpi-card kpi-arch"><div class="kpi-label">Architectural Changes</div><div class="kpi-value">{architectural_count}</div><div class="kpi-sub">{arch_pct:.0f}% of total</div></div>')
    # KPI: Issues
    w(f'<div class="kpi-card kpi-warn"><div class="kpi-label">Issues</div><div class="kpi-value">{issues_count}</div><div class="kpi-sub">{issues_pct:.0f}% of total</div></div>')
    # KPI: Manual Review
    w(f'<div class="kpi-card kpi-warn"><div class="kpi-label">Manual Review</div><div class="kpi-value">{manual_review}</div><div class="kpi-sub">{manual_review_pct:.0f}% of total</div></div>')
    # KPI: Failed
    w(f'<div class="kpi-card kpi-error"><div class="kpi-label">Failed</div><div class="kpi-value">{failed}</div><div class="kpi-sub">{failed_pct:.0f}% of total</div></div>')
    # KPI: Migration Score
    import math as _math
    ring_color = "#22c55e" if norm_score >= 80 else ("#f59e0b" if norm_score >= 50 else "#ef4444")
    ring_circ = 2 * _math.pi * 36
    ring_off = ring_circ * (1 - norm_score / 100)
    w(f'<div class="kpi-card kpi-score"><div class="kpi-label">Migration Score</div><div class="kpi-value" style="display:flex;align-items:center;gap:12px"><svg width="72" height="72" viewBox="0 0 80 80"><circle cx="40" cy="40" r="36" fill="none" stroke="var(--border)" stroke-width="6"/><circle cx="40" cy="40" r="36" fill="none" stroke="{ring_color}" stroke-width="6" stroke-dasharray="{ring_circ}" stroke-dashoffset="{ring_off}" stroke-linecap="round" transform="rotate(-90,40,40)"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="20" font-weight="700" fill="var(--text)">{norm_score}</text></svg></div><div class="kpi-sub">/ 100</div></div>')
    # KPI: Info & Warnings (cross-cutting, not exclusive)
    w(f'<div class="kpi-card kpi-warn"><div class="kpi-label">Info / Warnings</div><div class="kpi-value">{info_warning_count}</div><div class="kpi-sub">informational messages</div></div>')
    # KPI: Enterprise Ready
    ready_text = "Ready" if norm_score >= 80 and manual_review == 0 and failed == 0 else "Conditional"
    ready_color = "#22c55e" if ready_text == "Ready" else "#f59e0b"
    w(f'<div class="kpi-card"><div class="kpi-label">Enterprise Ready</div><div class="kpi-value" style="color:{ready_color}">{_h(ready_text)}</div><div class="kpi-sub">{total_passing}/{total_objects} objects passing</div></div>')
    w("</div></div>")

    # ── 2. Object Inventory ──
    w(f'<div class="section" id="inventory">')
    w(f'<h2 class="section-title">Object Inventory <span class="count-badge">{total_objects} total</span></h2>')
    w('<div class="type-grid">')
    for t, count in type_items:
        stats = type_stats.get(t.lower(), {"total": 0, "passed": 0, "warnings": 0, "errors": 0})
        pct = round(stats["passed"] / max(stats["total"], 1) * 100)
        w(f'<div class="type-card">')
        w(f'<div class="type-name">{_h(t)}</div>')
        w(f'<div class="type-stats"><span>&#x2713; {stats["passed"]}</span><span style="color:var(--warning)">&#x26A0; {stats["warnings"]}</span><span style="color:var(--error)">&#x2716; {stats["errors"]}</span></div>')
        w(f'<div class="type-bar"><div class="type-bar-fill" style="width:{pct}%;background:{["#ef4444","#f59e0b","#22c55e"][1 if pct < 80 else 0 if pct < 50 else 2]}"></div></div>')
        w("</div>")
    w("</div></div>")

    # ── 3. Migration Summary (Progress Bars) ──
    w(f'<div class="section" id="summary">')
    w('<h2 class="section-title">Migration Summary</h2>')
    w('<div class="card"><div class="card-body"><div class="progress-list">')
    for label, pct in progress_data:
        color = "#22c55e" if pct >= 80 else ("#f59e0b" if pct >= 40 else "#ef4444")
        w(f'<div class="progress-item"><span class="plabel">{_h(label)}</span><div class="pbar"><div class="pbar-fill" style="width:{pct}%;background:{color}"></div></div><span class="ppct">{pct}%</span></div>')
    w("</div></div></div></div>")

    # ── 4. Architecture Mapping ──
    w(f'<div class="section" id="arch-mapping">')
    w('<h2 class="section-title">Architecture Mapping</h2>')
    w('<p style="font-size:13px;color:var(--text-secondary);margin-bottom:12px">How Snowflake platform objects map to Databricks equivalents.</p>')
    w('<div class="arch-grid">')
    for src, dst, note in _ARCH_MAP:
        w('<div class="arch-card">')
        w(f'<div class="arch-src">{_h(src)}</div>')
        w(f'<div class="arch-arrow">&darr; &rarr;</div>')
        w(f'<div class="arch-dst">{_h(dst)}</div>')
        w(f'<div class="arch-note">{_h(note)}</div>')
        w("</div>")
    w("</div></div>")

    # ── 5. Object Status Table ──
    w(f'<div class="section" id="objects">')
    w('<h2 class="section-title">Object Status</h2>')
    w('<div class="search-bar">')
    w('<input type="text" id="search-input" placeholder="Search objects by name...">')
    w('<select id="status-filter"><option value="all">All Statuses</option><option value="PASS">PASS</option><option value="WARNING">WARNING</option><option value="ISSUE">ISSUE</option><option value="ERROR">ERROR</option><option value="ARCHITECTURAL CHANGE">ARCHITECTURAL</option></select>')
    w("</div>")
    w('<div class="card"><div class="card-body table-wrap">')
    w('<table id="object-table"><thead><tr>')
    for i, col in enumerate(["Status", "Object", "Type", "Confidence", "Review Needed", "Category", "File"]):
        w(f'<th data-col="{i}">{_h(col)} <span class="sort-icon"></span></th>')
    w("</tr></thead><tbody>")
    w("\n".join(table_rows))
    w("</tbody></table>")
    w('<div id="no-results" class="no-results" style="display:none">No objects match your search.</div>')
    w("</div></div></div>")

    # ── 6. Object Details ──
    w(f'<div class="section" id="details">')
    w('<h2 class="section-title">Object Details</h2>')
    for type_label, cards_html in detail_cards:
        w(f'<h3 style="font-size:16px;font-weight:600;margin:16px 0 8px;color:var(--text-secondary)">{_h(type_label)}</h3>')
        w(cards_html)
    w("</div>")

    # ── 7. Dependency Graph ──
    w(f'<div class="section" id="dependencies">')
    w('<h2 class="section-title">Dependency Graph</h2>')
    w('<div class="card"><div class="card-body" style="overflow-x:auto">')
    if dep_graph.cycles:
        w(f'<div style="padding:8px 12px;margin-bottom:12px;background:var(--warning-bg);border-radius:var(--radius);font-size:13px;color:var(--warning)">Circular dependencies detected: {_h(", ".join(dep_graph.cycles))}</div>')
    w(svg_dep)
    w("</div></div></div>")

    # ── 8. Issues ──
    w(f'<div class="section" id="issues">')
    w(f'<h2 class="section-title">Issues <span class="count-badge">{len(issue_cards)} issues</span></h2>')
    w('<div class="issue-list">')
    for sev, obj_name, msg in issue_cards:
        w(f'<div class="issue-card"><div class="sev sev-{sev}"></div><div class="ic-body"><div class="ic-obj">{_h(obj_name)}</div><div class="ic-msg">{msg}</div></div></div>')
    w("</div></div>")

    # ── 9. Final Summary ──
    w(f'<div class="section" id="final">')
    w('<div class="summary-card">')
    w(f'<div class="score-value" style="color:{ring_color}">{norm_score}</div>')
    w('<div class="score-label">Overall Migration Score</div>')
    w('<div class="rec">')
    w('<h4>Recommendation</h4>')
    ready_text = "Ready to proceed with deployment." if norm_score >= 80 and manual_review == 0 else "Manual review required before deployment."
    w(f'<p style="font-size:13px;color:var(--text-secondary);margin-bottom:8px">{_h(ready_text)}</p>')
    if rec_types:
        w("<ul>")
        w(f"<li><strong>{total_objects} total objects</strong> across {len(type_items)} types</li>")
        w(f"<li>{auto_conv} automatically converted ({auto_pct:.0f}%)</li>")
        w(f"<li>{architectural_count} architectural changes ({arch_pct:.0f}%)</li>")
        w(f"<li>{issues_count} with issues ({issues_pct:.0f}%)</li>")
        w(f"<li>{manual_review} need manual review ({manual_review_pct:.0f}%)</li>")
        w(f"<li>{failed} failed ({failed_pct:.0f}%)</li>")
        w("</ul>")
    w("</div></div></div>")

    w("</div>")  # layout

    # Embedded data
    w(f'<script id="report-data" type="application/json">')
    w(json.dumps({"total": total_objects, "project": project_name}))
    w("</script>")
    w(f"<script>{_JS}</script>")
    w("</body></html>")

    return "\n".join(parts)


def generate_migration_report(
    inventory: ProjectInventory,
    dep_graph: DependencyGraph,
    validation_results: dict[str, ValidationResult],
    output_dir: Path,
) -> Path:
    summary = inventory.summary()
    ACH = "ARCHITECTURAL CHANGE"

    val_summary = {
        "total": len(validation_results),
        "passed": sum(1 for r in validation_results.values() if r.is_pass()),
        "errors": sum(1 for r in validation_results.values() if r.status == "ERROR"),
        "issues": sum(1 for r in validation_results.values() if r.status == "ISSUE"),
        "warnings": sum(1 for r in validation_results.values() if r.status == "WARNING"),
        "architectural": sum(1 for r in validation_results.values() if r.status == ACH),
    }
    val_summary["pass_rate"] = (
        f"{val_summary['passed'] / val_summary['total'] * 100:.1f}%"
        if val_summary["total"] > 0 else "N/A"
    )

    # Mutually exclusive categories (each object counted exactly once)
    auto_conv = 0
    manual_review = 0
    architectural_count = 0
    issues_count = 0
    failed = 0
    for r in validation_results.values():
        if r.status == "ERROR":
            failed += 1
        elif r.status == "ISSUE":
            issues_count += 1
        elif r.status == "ARCHITECTURAL CHANGE":
            architectural_count += 1
        elif r.status == "WARNING":
            manual_review += 1
        elif r.is_pass():
            auto_conv += 1

    # Cross-cutting metrics (overlap, not exclusive)
    _INFO_WARNINGS = {
        "PRIMARY KEY is informational",
        "FOREIGN KEY is informational",
        "VARIANT column(s) converted",
        "SECURE VIEW access controls lost",
        "Syntax error expected (architectural change)",
    }
    info_warning_count = 0
    for r in validation_results.values():
        for w in r.warnings:
            if any(kw in w for kw in _INFO_WARNINGS):
                info_warning_count += 1

    total_val = max(val_summary["total"], 1)
    auto_pct = auto_conv / total_val * 100
    manual_review_pct = manual_review / total_val * 100
    arch_pct = architectural_count / total_val * 100
    issues_pct = issues_count / total_val * 100
    failed_pct = failed / total_val * 100
    info_pct = info_warning_count / total_val * 100

    complexity_buckets = {"Easy": 0, "Medium": 0, "Hard": 0, "Expert": 0}
    complexity_total = 0
    for obj in inventory.all_objects:
        r = validation_results.get(obj.name)
        label, score = _complexity_level(obj, r)
        complexity_buckets[label] = complexity_buckets.get(label, 0) + 1
        complexity_total += score
    avg_complexity = round(complexity_total / max(len(inventory.all_objects), 1), 1)
    norm_score = max(0, min(100, round((1 - avg_complexity / 15) * 100)))

    type_counts: dict[str, int] = {}
    for obj in inventory.all_objects:
        key = OBJECT_TYPE_LABELS.get(obj.object_type, obj.object_type)
        type_counts[key] = type_counts.get(key, 0) + 1
    type_items = sorted(type_counts.items(), key=lambda x: -x[1])

    ordered = dep_graph.get_deployment_order()

    html = _build_html(
        summary=summary,
        inventory=inventory,
        ordered=ordered,
        validation_results=validation_results,
        dep_graph=dep_graph,
        val_summary=val_summary,
        auto_conv=auto_conv,
        info_warning_count=info_warning_count,
        manual_review=manual_review,
        architectural_count=architectural_count,
        issues_count=issues_count,
        failed=failed,
        auto_pct=auto_pct,
        info_pct=info_pct,
        manual_review_pct=manual_review_pct,
        arch_pct=arch_pct,
        issues_pct=issues_pct,
        failed_pct=failed_pct,
        complexity_buckets=complexity_buckets,
        avg_complexity=avg_complexity,
        norm_score=norm_score,
        type_items=type_items,
    )

    report_path = output_dir / "migration_report.html"
    report_path.write_text(html, encoding="utf-8")
    return report_path


def generate_object_inventory_csv(
    inventory: ProjectInventory, output_dir: Path
) -> Path:
    csv_path = output_dir / "object_inventory.csv"
    lines = ["object_type,object_name,schema_name,source_file,status"]
    for obj in inventory.all_objects:
        schema = obj.schema_name or ""
        status = "converted" if obj.converted_sql else "pending"
        lines.append(
            f"{obj.object_type},{obj.name},{schema},{obj.file_path},{status}"
        )
    csv_path.write_text("\n".join(lines), encoding="utf-8")
    return csv_path


def generate_dependency_diagram(dep_graph: DependencyGraph, output_dir: Path) -> Path:
    diagram_path = output_dir / "dependency_diagram.txt"
    lines = ["Dependency Diagram", "=" * 50, ""]
    ordered = dep_graph.get_deployment_order()
    for obj in ordered:
        deps = dep_graph.edges.get(obj.name.lower(), [])
        if deps:
            dep_names = ", ".join(deps)
            lines.append(f"  {obj.name}  -->  [{dep_names}]")
        else:
            lines.append(f"  {obj.name}  (no dependencies)")
    diagram_path.write_text("\n".join(lines), encoding="utf-8")
    return diagram_path
