import re
from parser.sql_parser import ParsedObject


def _convert_create_table_sql(sql: str) -> str:
    sql = re.sub(
        r"CREATE\s+(?:OR\s+REPLACE\s+)?TABLE",
        "CREATE OR REPLACE TABLE",
        sql,
        count=1,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"(?i)AUTOINCREMENT\s*(?:\([^)]*\))?", "", sql)
    sql = re.sub(r"(?i)AUTO_INCREMENT", "", sql)
    sql = re.sub(r"(?i)DEFAULT\s+(?:\w+\.)*\w+\.NEXTVAL", "GENERATED BY DEFAULT AS IDENTITY", sql)
    sql = re.sub(
        r"(?i)(\w+)\s+\w+(?:\s*\([^)\n]*\))?(\s+(?:NOT\s+)?NULL\s+GENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY)",
        r"\1 BIGINT\2",
        sql,
    )
    sql = re.sub(r"(?i)DATA_RETENTION_TIME_IN_DAYS\s*=\s*\d+", "", sql)
    # Remove TBLPROPERTIES clause when it only contains Snowflake-specific settings
    sql = re.sub(r"\s*TBLPROPERTIES\s*\([^)]*DATA_RETENTION_TIME_IN_DAYS[^)]*\)", "", sql)
    sql = re.sub(r"\s+,", ",", sql)
    sql = re.sub(r",\s*\)", ")", sql)
    # Add delta.feature.allowColumnDefaults to support column DEFAULT values
    if re.search(r"\bDEFAULT\b", sql, re.IGNORECASE) and "delta.feature.allowColumnDefaults" not in sql:
        sql = re.sub(
            r"(?i)(USING\s+DELTA)",
            r"\1 TBLPROPERTIES('delta.feature.allowColumnDefaults' = 'supported')",
            sql,
        )
    return sql


def _convert_create_schema_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?SCHEMA\s+(?:IF\s+NOT\s+EXISTS\s+)?",
        "CREATE SCHEMA IF NOT EXISTS ",
        sql,
    )
    return sql


def _convert_create_view_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?(?:SECURE\s+)?VIEW",
        "CREATE OR REPLACE VIEW",
        sql,
    )
    return sql


def _convert_update_from_to_merge(body: str) -> str:
    """
    Deterministic transpiler: Snowflake UPDATE ... FROM → Databricks MERGE INTO.

    Snowflake:
        UPDATE target T
        SET col1 = S.col1, col2 = S.col2
        FROM (
            SELECT id, col1, col2 FROM source
        ) S
        WHERE T.id = S.id;

    Databricks:
        MERGE INTO target T
        USING (
            SELECT id, col1, col2 FROM source
        ) S
        ON T.id = S.id
        WHEN MATCHED THEN UPDATE SET
          col1 = S.col1, col2 = S.col2;
    """

    def _find_balanced_end(text, start):
        depth = 0
        for i in range(start, len(text)):
            if text[i] == '(':
                depth += 1
            elif text[i] == ')':
                depth -= 1
                if depth == 0:
                    return i + 1
        return -1

    def _find_keyword(text, keyword, start=0):
        depth = 0
        kw = keyword.upper()
        i = start
        while i < len(text):
            c = text[i]
            if c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
            elif depth == 0 and text[i:].upper().startswith(kw):
                before_ok = i == 0 or not text[i - 1].isalnum()
                after_pos = i + len(kw)
                after_ok = after_pos >= len(text) or not text[after_pos].isalnum()
                if before_ok and after_ok:
                    return i
            i += 1
        return -1

    result = body
    offset = 0

    while True:
        update_pos = _find_keyword(result, "UPDATE", offset)
        if update_pos == -1:
            break

        set_pos = _find_keyword(result, "SET", update_pos + 7)
        if set_pos == -1 or set_pos - update_pos > 200:
            offset = update_pos + 7
            continue

        from_pos = _find_keyword(result, "FROM", set_pos + 4)
        if from_pos == -1 or from_pos - set_pos > 2000:
            offset = set_pos + 4
            continue

        where_pos = _find_keyword(result, "WHERE", from_pos + 5)
        if where_pos == -1:
            offset = from_pos + 5
            continue

        target_text = result[update_pos + 7 : set_pos].strip()
        target_parts = target_text.split(None, 1)
        target_table = target_parts[0]
        target_alias = (
            target_parts[1].strip()
            if len(target_parts) > 1
            else target_table.split(".")[-1]
        )

        set_clauses = result[set_pos + 4 : from_pos].strip()

        from_text = result[from_pos + 5 : where_pos].strip()

        if from_text.startswith("("):
            close = _find_balanced_end(from_text, 0)
            if close == -1:
                offset = from_pos + 5
                continue
            source_query = from_text[1 : close - 1].strip()
            rest = from_text[close:].strip()
            source_alias = rest.split()[0] if rest else "src"
        else:
            tokens = from_text.split(None, 2)
            source_query = tokens[0]
            source_alias = (
                tokens[1] if len(tokens) > 1 else source_query.split(".")[-1]
            )

        where_end = result.find(";", where_pos)
        if where_end == -1:
            where_end = len(result)
        where_condition = result[where_pos + 6 : where_end].strip()

        merge = f"MERGE INTO {target_table} {target_alias}\n"
        if source_query.upper().lstrip().startswith("SELECT"):
            merge += f"USING ({source_query}) {source_alias}\n"
        else:
            merge += f"USING {source_query} {source_alias}\n"
        merge += f"ON {where_condition}\n"
        merge += f"WHEN MATCHED THEN UPDATE SET\n  {set_clauses};"

        result = result[:update_pos] + merge + result[where_end + 1 :]
        offset = update_pos + len(merge)

    return result


def _convert_procedure_body(body: str) -> str:
    # Convert LET var := expr to SET var = expr (assignment, not declaration)
    body = re.sub(r"(?i)\bLET\s+(\w+)\s*:=\s*", r"SET \1 = ", body)
    # Convert remaining LET (declarations without assignment) to DECLARE
    body = re.sub(r"(?i)\bLET\s+", "DECLARE ", body)
    body = re.sub(r"(?i)(INTO)\s+:(\w+)", r"\1 \2", body)
    body = re.sub(r"(?<![:\w']):(\w+)", r"\1", body)
    body = re.sub(r";;\s*", "; ", body)
    # Convert Snowflake SQLROWCOUNT to Databricks GET DIAGNOSTICS pattern
    # Snowflake: SET var = SQLROWCOUNT;
    # Databricks: GET DIAGNOSTICS var = ROW_COUNT;
    body = re.sub(
        r"(?i)SET\s+(\w+)\s*=\s*SQLROWCOUNT\b",
        r"GET DIAGNOSTICS \1 = ROW_COUNT",
        body,
    )
    # Fallback: bare SQLROWCOUNT references
    body = re.sub(r"(?i)SQLROWCOUNT", "ROW_COUNT", body)
    # Convert var := expr to SET var = expr (Databricks SQL syntax)
    body = re.sub(r"(?i)(\w+)\s*:=\s*", r"SET \1 = ", body)
    # Convert Snowflake SELECT col INTO var FROM ... ; to Databricks SET var = (SELECT col FROM ...);
    body = re.sub(
        r"(?i)SELECT\s+(.+?)\s+INTO\s+(\w+)\s+(FROM\s+.+?)\s*;",
        r"SET \2 = (SELECT \1 \3);",
        body,
    )
    # Convert Snowflake TEMPORARY TABLE → Databricks TEMPORARY VIEW
    # Databricks SQL Warehouse doesn't support CREATE TEMPORARY TABLE
    # Also: Databricks temp views only accept single-part names (no catalog.schema prefix)
    body = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?TEMPORARY\s+TABLE\s+(\w+(?:\.\w+)*)",
        lambda m: "CREATE OR REPLACE TEMPORARY VIEW " + m.group(1).split(".")[-1],
        body,
    )
    # Convert Snowflake UPDATE ... FROM → Databricks MERGE INTO
    body = _convert_update_from_to_merge(body)
    return body


def _convert_create_procedure_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?PROCEDURE",
        "CREATE OR REPLACE PROCEDURE",
        sql,
    )
    # Remove LANGUAGE SQL (redundant — inferred by Databricks)
    sql = re.sub(r"(?i)\s*LANGUAGE\s+SQL\s*", "\n", sql)
    # Remove RETURNS clause (not supported on Databricks SQL Warehouse)
    sql = re.sub(r"(?i)\s*RETURNS\s+\w+(?:\s*\([^)]*\))?\s*", "\n", sql)
    # Remove EXECUTE AS OWNER/CALLER
    sql = re.sub(r"(?i)\s*EXECUTE\s+AS\s+(?:OWNER|CALLER)", "", sql)
    # Collapse blank lines before inserting SQL SECURITY
    sql = re.sub(r"\n{3,}", "\n\n", sql)
    # Add SQL SECURITY INVOKER (required by Databricks SQL Warehouse)
    sql = re.sub(r"(?i)(\))\s+AS\b", r"\1\nSQL SECURITY INVOKER\nAS", sql, count=1)
    # Convert Snowflake AS $$body$$ to Databricks AS\nbody
    dollar_match = re.search(r"AS\s*\$\$\s*\n?(.*?)\n?\s*\$\$", sql, re.DOTALL)
    if dollar_match:
        before_body = sql[:dollar_match.start(0)].rstrip()
        body = dollar_match.group(1).strip()
        body = _convert_procedure_body(body)
        # Convert RETURN 'msg' to SELECT 'msg' (RETURN requires RETURNS clause)
        body = re.sub(r"(?i)^\s*RETURN\s+", "SELECT ", body)
        body = re.sub(r"(?i)(?<!\w)RETURN\s+", "SELECT ", body)
        # Move DECLARE block inside BEGIN
        body = re.sub(
            r"(?is)DECLARE\s+(.*?)BEGIN",
            lambda m: "BEGIN\n  DECLARE " + m.group(1).strip().replace("\n    ", "\n    "),
            body,
        )
        # Wrap in BEGIN...END if not already present
        if not re.search(r"(?i)\bBEGIN\b", body):
            body = "BEGIN\n  " + body.replace("\n", "\n  ") + "\nEND;"
        sql = before_body + "\nAS\n" + body
    else:
        # Convert Snowflake AS 'body' to Databricks AS\nbody
        match = re.search(r"AS\s*'(.*)'\s*$", sql, re.DOTALL)
        if match:
            before_body = sql[:match.start(0)].rstrip()
            body = match.group(1)
            body = body.replace("\\'", "'").replace("\\n", "\n")
            body = body.replace("''", "'")
            body = _convert_procedure_body(body)
            # Convert RETURN 'msg' to SELECT 'msg' (RETURN requires RETURNS clause)
            body = re.sub(r"(?i)^\s*RETURN\s+", "SELECT ", body)
            body = re.sub(r"(?i)(?<!\w)RETURN\s+", "SELECT ", body)
            # Move DECLARE block inside BEGIN
            body = re.sub(
                r"(?is)DECLARE\s+(.*?)BEGIN",
                lambda m: "BEGIN\n  DECLARE " + m.group(1).strip().replace("\n    ", "\n    "),
                body,
            )
            sql = before_body + "\nAS\n" + body

    sql = re.sub(r"\n{3,}", "\n\n", sql)

    # Final safety net: fix LLM or edge-case regressions
    sql = re.sub(r"(?i)\bSQL\s+SECURITY\s+DEFINER\b", "SQL SECURITY INVOKER", sql)
    sql = re.sub(r"(?i)\bRETURN\s+'", "SELECT '", sql)
    sql = re.sub(r"(?i)\bRETURN\s+\"", 'SELECT "', sql)
    # Databricks does not allow double-quoted procedure/function names — use backticks
    sql = re.sub(
        r'(CREATE\s+OR\s+REPLACE\s+(?:PROCEDURE|FUNCTION)\s+)(\"[^\"]+\")',
        lambda m: m.group(1) + "`" + m.group(2).strip('"') + "`",
        sql,
    )

    needs_review = []
    if re.search(r"RESULT_SCAN", sql, re.IGNORECASE):
        needs_review.append("RESULT_SCAN() has no Databricks equivalent")
    if re.search(r"EXECUTE\s+IMMEDIATE", sql, re.IGNORECASE):
        needs_review.append("EXECUTE IMMEDIATE needs manual conversion")
    if re.search(r"LANGUAGE\s+JAVASCRIPT", sql, re.IGNORECASE):
        needs_review.append("JavaScript body requires manual conversion to Python or Scala")
    # Only flag UPDATE FROM if _convert_update_from_to_merge couldn't handle it
    if re.search(r"UPDATE\s+\S+(?:\s+\w+)?\s+SET\s+.+?\s+FROM\s+", sql, re.IGNORECASE | re.DOTALL):
        needs_review.append("UPDATE FROM not supported in Databricks SQL — use MERGE INTO instead")

    if needs_review:
        sql = sql.strip()
        sql += "\n\n-- MANUAL REVIEW REQUIRED: " + "; ".join(needs_review)

    return sql.strip()


def _convert_create_function_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?(?:SECURE\s+)?FUNCTION",
        "CREATE OR REPLACE FUNCTION",
        sql,
    )
    if re.search(r"\bLANGUAGE\s+JAVASCRIPT\b", sql, re.IGNORECASE):
        sql = re.sub(r"\$\$", "", sql)
        sql += (
            "\n-- ARCHITECTURAL CHANGE: JavaScript UDF body requires manual conversion to Python or Scala\n"
            "-- MANUAL REVIEW REQUIRED"
        )
        return sql

    # Handle $$ bodies (existing logic)
    if re.search(r"\$\$", sql):
        sql = re.sub(r"(?i)(AS)\s*\n?\s*\$\$", r"RETURN", sql)
        sql = re.sub(r"\$\$", "", sql)
        sql = re.sub(r";\s*;\s*", ";", sql)
        return sql

    # Handle Snowflake AS 'body' syntax
    match = re.search(r"(?i)(LANGUAGE\s+SQL)\s+AS\s*'(.*)'\s*$", sql, re.DOTALL)
    if match:
        before = sql[:match.start(1)]
        body = match.group(2)
        body = body.replace("\\'", "'").replace("\\n", "\n")
        body = body.replace("''", "'")
        body = body.strip()
        return f"{before}LANGUAGE SQL\nRETURN {body}"

    return sql


def _convert_create_external_table_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?EXTERNAL\s+TABLE",
        "CREATE OR REPLACE TABLE",
        sql,
        count=1,
    )
    sql = re.sub(r"(?i)FILE_FORMAT\s*=\s*\([^)]*\)", "", sql)
    sql = re.sub(r"(?i)LOCATION\s*=\s*", "LOCATION ", sql)
    sql = re.sub(r"\s+", " ", sql).strip()
    sql += (
        "\n\n-- ARCHITECTURAL CHANGE: External table converted to managed Delta table. "
        "Review LOCATION and data access pattern.\n"
        "-- MANUAL REVIEW REQUIRED"
    )
    return sql


def _convert_create_stage_sql(sql: str) -> str:
    # Snowflake stages → Databricks Volumes (closest equivalent)
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?(?:TEMPORARY\s+|TEMP\s+)?STAGE",
        "CREATE VOLUME",
        sql,
        count=1,
    )
    sql = re.sub(r"(?i)FILE_FORMAT\s*=\s*\([^)]*\)", "", sql)
    sql = re.sub(r"(?i)\s+ENCRYPTION\s*=\s*\([^)]*\)", "", sql)
    sql = re.sub(r"\s+", " ", sql).strip()
    sql += (
        "\n\n-- ARCHITECTURAL CHANGE: Snowflake STAGE converted to Databricks VOLUME. "
        "Verify storage location and access credentials.\n"
        "-- MANUAL REVIEW REQUIRED"
    )
    return sql


def _convert_create_materialized_view_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?(?:SECURE\s+)?MATERIALIZED\s+VIEW",
        "CREATE MATERIALIZED VIEW",
        sql,
        count=1,
    )
    sql += (
        "\n\n-- NOTE: Databricks materialized views require a Pro or Serverless SQL Warehouse. "
        "Refresh with: ALTER MATERIALIZED VIEW name REFRESH\n"
        "-- MANUAL REVIEW REQUIRED"
    )
    return sql


def _convert_create_sequence_sql(sql: str) -> str:
    sql = re.sub(
        r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?SEQUENCE",
        "CREATE SEQUENCE",
        sql,
        count=1,
    )
    return sql


def convert_schema(obj: ParsedObject) -> str:
    sql = obj.converted_sql if obj.converted_sql else obj.raw_sql

    if obj.object_type == "table":
        return _convert_create_table_sql(sql)
    elif obj.object_type == "view":
        return _convert_create_view_sql(sql)
    elif obj.object_type == "schema":
        return _convert_create_schema_sql(sql)
    elif obj.object_type == "procedure":
        return _convert_create_procedure_sql(sql)
    elif obj.object_type == "function":
        return _convert_create_function_sql(sql)
    elif obj.object_type == "external_table":
        return _convert_create_external_table_sql(sql)
    elif obj.object_type == "stage":
        return _convert_create_stage_sql(sql)
    elif obj.object_type == "materialized_view":
        return _convert_create_materialized_view_sql(sql)
    elif obj.object_type == "sequence":
        return _convert_create_sequence_sql(sql)
    else:
        return sql
